---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_lustre:
  project_name: lustre
  os_version: "el9"
  os_minor_version: "4"
  domain: "jtest.ddn.com"
  rdomain: "com.ddn.jtest"
  cluster_name: jack-kr-lustre
  major_version: "2"
  minor_version: "16"
  patch_version: "0"
  build_version: "0"
  download_url: "https://downloads.whamcloud.com/public/lustre"
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  nvme: true
  net:
    conn: "dpdk"                     # dpdk or udp
    gateway: "192.168.2.1"
    ha1: 1
    ha2: 2
    type: "virtual"                  # or physical
    ipaddr0: "192.168.0.2"
    ipaddr1: "192.168.1.2"
    ipaddr2: "192.168.2.2"
  backend:
    net:
      type: "virtual"                # or physical
      ipaddr0: "192.168.0.2"
      ipaddr1: "192.168.1.2"
      ipaddr2: "192.168.2.2"
  client:
    net:
      type: "virtual"                # or physical
      cores: 1
      ipaddr0: "192.168.0.2"
      ipaddr1: "192.168.1.2"
      ipaddr2: "192.168.2.2"
  vms:
    rk9: [ "rk9-freeipa", "rk94-node99", "rk94-node00", "rk94-node01", "rk94-node02", "rk94-node03", "rk94-node04", "rk94-node05", "rk94-node06", "rk94-node07", "rk94-node08", "rk94-node09", "rk94-node10" ]
    ubt24: [ "rk9-freeipa", "ubt24-node06", "ubt24-node07", "ubt24-node08", "ubt24-node09" ]


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

