---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_lustre:
  project_name: lustre
  os_version: "el9"
  os_minor_version: "4"
  domain: "jtest.ddn.com"
  rdomain: "com.ddn.jtest"
  cluster_name: jack-kr-lustre
  major_version: "2"
  minor_version: "16"
  patch_version: "0"
  build_version: "0"
  download_url: "https://downloads.whamcloud.com/public/lustre"
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  nvme: true
  net:
    conn: "dpdk"                     # dpdk or udp
    gateway: "192.168.2.1"
    ha1: 1
    ha2: 2
    type: "virtual"                  # or physical
    ipaddr0: "192.168.0.2"
    ipaddr1: "192.168.1.2"
    ipaddr2: "192.168.2.2"
  backend:
    net:
      type: "virtual"                # or physical
      ipaddr0: "192.168.0.2"
      ipaddr1: "192.168.1.2"
      ipaddr2: "192.168.2.2"
  client:
    net:
      type: "virtual"                # or physical
      cores: 1
      ipaddr0: "192.168.0.2"
      ipaddr1: "192.168.1.2"
      ipaddr2: "192.168.2.2"
  vms:
    rk9: [ "rk9-freeipa", "rk94-node99", "rk94-node00", "rk94-node01", "rk94-node02", "rk94-node03", "rk94-node04", "rk94-node05", "rk94-node06", "rk94-node07", "rk94-node08", "rk94-node09", "rk94-node10", "co7-node01" ] # 192.168.2.71
    ubt24: [ "rk9-freeipa", "ubt24-node06", "ubt24-node07", "ubt24-node08", "ubt24-node09" ]


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


pgsql:
  cluster_name: jack-kr-pgsql
  major_version: "17"
  minor_version: ""
  patch_version: ""
  build_version: ""
  os_version: el9
  arch_type: x86_64
  bin_type: rpm
  db_name: pgsql_testdb
  db_user: jomoon
  user: postgres
  group: postgres
  db_password: 'changeme'
  sudo_user_dir: "/home/jomoon"
  home_dir: "/home/postgres"
  base_dir: "/var/lib/pgsql"
  domain: "jtest.ddn.com"
  repo_url: ""
  download_url: ""
  download: false
  host_num: "{{ groups['all'] | length }}"
  base_path: /root
  enable_ssl: true
  # with_patroni_pkg: True
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.2"
    ipaddr1: "192.168.1.2"
    ipaddr2: "192.168.2.2"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.2"
      ipaddr1: "192.168.1.2"
      ipaddr2: "192.168.2.2"
  debug_opt: ""  # --debug


common:
  sudo_user: jomoon
  sudo_group: jomoon
  sudo_user_home_dir: "/home/jomoon"
  pgsql_bin_dir: "/usr/pgsql-{{ pgsql.major_version }}/bin"
  pgsql_pkg_name: "vmware-postgres{{ pgsql.major_version }}"
  # pgsql_bin_dir: "/opt/vmware/postgres/{{ pgsql.major_version }}/bin"
  # pgsql_pkg_name: pivotal-postgres


