---
_cluster:
  lnet:
    - { suffix: "@tcp2", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }
  mgs:
    - { dev_prefix: "/dev/mapper", dev: "dt111", phy_dev: "sda", mnt_dir: "/lustre/mgs0", idx_id: "0", fs: "tfs1", node: "rk94-node01" }
  mdts:
    - { dev_prefix: "/dev/mapper", dev: "dt122", phy_dev: "sda", idx_id: "1", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node02" }
    - { dev_prefix: "/dev/mapper", dev: "dt211", phy_dev: "sda", idx_id: "0", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node03" }
    - { dev_prefix: "/dev/mapper", dev: "dt222", phy_dev: "sda", idx_id: "0", fs: "tfs3", lnet_suffix: "@tcp2", node: "rk94-node04" }
  osts:
    - { dev_prefix: "/dev/mapper", dev: "dt311", phy_dev: "sda", idx_id: "2", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node05" }
    - { dev_prefix: "/dev/mapper", dev: "dt322", phy_dev: "sda", idx_id: "3", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node06" }
    - { dev_prefix: "/dev/mapper", dev: "dt411", phy_dev: "sda", idx_id: "4", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node07" }
    - { dev_prefix: "/dev/mapper", dev: "dt422", phy_dev: "sda", idx_id: "5", fs: "tfs3", lnet_suffix: "@tcp2", node: "rk94-node08" }
  client:
    - { lnet_suffix: "@tcp2", mount_prefix: "/mnt/lustre0", fs_name: "tfs1", mgsnode: "{{ hostvars[groups['mgs'][0]]['ansible_ssh_host'] }}", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }
    - { lnet_suffix: "@tcp2", mount_prefix: "/mnt/lustre1", fs_name: "tfs2", mgsnode: "{{ hostvars[groups['mgs'][0]]['ansible_ssh_host'] }}", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }
    - { lnet_suffix: "@tcp2", mount_prefix: "/mnt/lustre2", fs_name: "tfs3", mgsnode: "{{ hostvars[groups['mgs'][0]]['ansible_ssh_host'] }}", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }


#_cluster:
#  lnet:
#    - { suffix: "@tcp2", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }
#  mgs:
#    - { dev_prefix: "/dev/mapper", dev: "dt111", phy_dev: "sda", mnt_dir: "/lustre/mgs0", idx_id: "0", fs: "tfs1", node: "rk94-node01" }
#  mdts:
#    - { dev_prefix: "/dev/mapper", dev: "dt122", phy_dev: "sda", idx_id: "1", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node02" }
#    - { dev_prefix: "/dev/mapper", dev: "dt211", phy_dev: "sda", idx_id: "0", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node03" }
#    - { dev_prefix: "/dev/mapper", dev: "dt222", phy_dev: "sda", idx_id: "1", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node04" }
#  osts:
#    - { dev_prefix: "/dev/mapper", dev: "dt311", phy_dev: "sda", idx_id: "2", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node05" }
#    - { dev_prefix: "/dev/mapper", dev: "dt322", phy_dev: "sda", idx_id: "3", fs: "tfs1", lnet_suffix: "@tcp2", node: "rk94-node06" }
#    - { dev_prefix: "/dev/mapper", dev: "dt411", phy_dev: "sda", idx_id: "4", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node07" }
#    - { dev_prefix: "/dev/mapper", dev: "dt422", phy_dev: "sda", idx_id: "5", fs: "tfs2", lnet_suffix: "@tcp2", node: "rk94-node08" }
#  client:
#    - { lnet_suffix: "@tcp2", mount_prefix: "/mnt/lustre0", fs_name: "tfs1", mgsnode: "{{ hostvars[groups['mgs'][0]]['ansible_ssh_host'] }}", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }
#    - { lnet_suffix: "@tcp2", mount_prefix: "/mnt/lustre1", fs_name: "tfs2", mgsnode: "{{ hostvars[groups['mgs'][0]]['ansible_ssh_host'] }}", net2: "{{ hostvars[groups['client'][0]]['ansible_ssh_host'] }}@tcp2" }

lustre_server: "{{ _cluster.mgs[0].node }}{{ _cluster.lnet[0].suffix }}"

