- name: Start MGS
  when:
    - lustre_format_mgs is defined
  block:
    - name: Create MGS mountpoint
      file:
        path: "{{ lustre_mount_prefix }}/MGS"
        state: directory

    - name: Mount MGS
      command: "mount -t lustre {{ lustre_format_mgs.device }} {{ lustre_mount_prefix }}/MGS"
      register: cmd_mgs_result
      failed_when: "cmd_mgs_result.rc != 0 and ('is already mounted' not in cmd_mgs_result.stderr)"
      changed_when: "cmd_mgs_result.rc == 0"


- name: Start MDTs
  when:
    - lustre_format_mdts is defined
  block:
    - name: Create MDT Mount Directory
      file:
        path: "{{ lustre_mount_prefix }}/{{ lustre_fsname }}-MDT{{ '%04x' % item.index | int }}"
        state: directory
      with_items: "{{ lustre_format_mdts }}"

    - name: mount MDTs
      command: "mount -t lustre {{ item.device }} {{ lustre_mount_prefix }}/{{ lustre_fsname }}-MDT{{ '%04x' % item.index | int }}"
      register: cmd_mgt_result
      failed_when: "cmd_mgt_result.rc != 0 and ('is already mounted' not in cmd_mgt_result.stderr)"
      changed_when: "cmd_mgt_result.rc == 0"
      with_items: "{{ lustre_format_mdts }}"


- name: Start OSTs
  when:
    - lustre_format_osts is defined
  block:
    - name: Create OST Mount Directory
      file:
        path: "{{ lustre_mount_prefix }}/{{ lustre_fsname }}-OST{{ '%04x' % item.index | int }}"
        state: directory
      with_items: "{{ lustre_format_osts }}"

    - name: Mount OSTs
      command: "mount -t lustre {{ item.device }} {{ lustre_mount_prefix }}/{{ lustre_fsname }}-OST{{ '%04x' % item.index | int }}"
      register: cmd_ost_result
      failed_when: "cmd_ost_result.rc != 0 and ('is already mounted' not in cmd_ost_result.stderr)"
      changed_when: "cmd_ost_result.rc == 0"
      with_items: "{{ lustre_format_osts }}"


