---
- name: Add Lustre Kernel Module
  modprobe:
    name: lustre
    state: present


- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive


- name: Rebuild Init RAM Disk
  shell:
    dracut  -f --regenerate-all


- name: Save Lustre Kernel Module
  template:
    src: lustre.conf.j2
    dest: "/etc/modules-load.d/{{ item }}.conf"
    mode: 0644
  with_items:
    - lustre


- name: Reboot Hosts to Apply New Kernel
  import_tasks: ext/reboot-hosts.yml

