---
#- name: Enable Lustre Client Repo
#  yum_repository:
#    name: lustre-client
#    description: lustre-client
#    file: lustre-repo
#    baseurl: "{{ _lustre.download_url }}/lustre-{{ lustre_version }}/{{ _lustre.os_version }}.{{ _lustre.os_minor_version }}/client"
#    gpgcheck: no
#  register: enable_client_repo


- name: Ensure Kernel Headers Available
  package:
    name: kernel-devel,epel-release,python3-dnf-plugin-versionlock
    # EPEL needed to install dkms


#- name: Unlock Kernel Version
#  import_tasks: ext/unlock-kernel-version.yaml


#- name: Install Lustre Client DKMS
#  yum:
#    name: "lustre-client-dkms-{{ lustre_version }}"
#    state: present


- name: Install Lustre Client kmods
  yum:
    name: "kmod-lustre-client-{{ lustre_version }}"
    state: present


- name: Install Lustre Client
  yum:
    name: "lustre-client-{{ lustre_version }}"
    state: present


#- name: Add Lustre Kernel Module
#  modprobe:
#    name: lustre
#    state: present


#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive


#- name: Rebuild Init RAM Disk
#  shell:
#    dracut  -f --regenerate-all


#- name: Reboot Hosts to Apply New Kernel
#  import_tasks: ext/reboot-hosts.yml

