---
#- name: Enable Lustre Server Repo
#  yum_repository:
#    name: lustre-server
#    description: lustre-server
#    file: lustre-repo
#    baseurl: "{{ _lustre.download_url }}/lustre-{{ lustre_version }}/{{ _lustre.os_version }}.{{ _lustre.os_minor_version }}/server"
#    gpgcheck: no
#
#
#- name: Enable Lustre e2fs Repo
#  yum_repository:
#    name: e2fsprogs-wc
#    description: e2fsprogs-wc
#    file: lustre-repo
#    baseurl: "https://downloads.whamcloud.com/public/e2fsprogs/latest/{{ _lustre.os_version }}"
#    gpgcheck: no


# dnf install lustre-ldiskfs-dkms-2.16.1


#- name: Install Lustre Kernel
#  package:
#    name: kernel-core-5.14.0-427.31.1_lustre.el9
#    state: present
#
#
#- name: Reboot Hosts to Apply New Kernel
#  import_tasks: ext/reboot-hosts.yml


- name: Ensure Kernel Headers Available
  package:
    name: kernel-devel,epel-release,python3-dnf-plugin-versionlock
    # EPEL needed to install dkms


#- name: Unlock Kernel Version
#  import_tasks: ext/unlock-kernel-version.yaml


#- name: Install Lustre All DKMS
#  yum:
#    name: "lustre-all-dkms-{{ lustre_version }}"
#    state: present


#- name: Install Lustre Kernel Module
#  yum:
#    name: "kmod-lustre-{{ lustre_version }},kmod-lustre-devel-{{ lustre_version }}"
#    state: present


- name: Install Lustre Server
  yum:
    name: "lustre-{{ lustre_version }}"
    state: present


- name: Add Lustre Kernel Module
  modprobe:
    name: lustre
    state: present


- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive


- name: Rebuild Init RAM Disk
  shell:
    dracut  -f --regenerate-all


- name: Save Lustre Kernel Module
  template:
    src: lustre.conf.j2
    dest: "/etc/modules-load.d/{{ item }}.conf"
    mode: 0644
  with_items:
    - lustre


- name: Reboot Hosts to Apply New Kernel
  import_tasks: ext/reboot-hosts.yml

