---
#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive


- name: Unlock Kernel Version
  import_tasks: ext/unlock-kernel-version.yaml


- name: Uninstall Lustre Client
  yum:
    name: "lustre-client-{{ lustre_version }}"
    state: absent


- name: Remove Lustre Kernel Module
  modprobe:
    name: lustre
    state: absent


- name: Uninstall Lustre Client kmods
  yum:
    name: "kmod-lustre-client-{{ lustre_version }}"
    state: absent


#- name: Uninstall Lustre Client DKMS
#  yum:
#    name: "lustre-client-dkms-{{ lustre_version }}"
#    state: absent


- name: Remove Kernel Headers Available
  package:
    name: kernel-devel
    state: absent


- name: Disable Lustre Client Repo
  yum_repository:
    name: lustre-client
    state: absent


- name: Delete Lustre Client Repo
  file:
    path: /etc/yum.repos.d/lustre-repo.repo
    state: absent

