---
#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive


- name: Unlock Kernel Version
  import_tasks: ext/unlock-kernel-version.yaml


- name: Uninstall Lustre Server
  yum:
    name: "lustre-{{ lustre_version }}"
    state: absent


#- name: Disable Lustre e2fs Repo
#  yum_repository:
#    name: e2fsprogs-wc
#    state: absent
#
#
#- name: Disable Lustre Server Repo
#  yum_repository:
#    name: lustre-server
#    state: absent


- name: Remove Lustre Kernel Module
  modprobe:
    name: lustre
    state: absent


- name: Uninstall Lustre Kernel Module
  yum:
    name: "kmod-lustre-{{ lustre_version }},kmod-lustre-devel-{{ lustre_version }}"
    state: absent


#- name: Uninstall Lustre All DKMS
#  yum:
#    name: "lustre-all-dkms-{{ lustre_version }}"
#    state: absent


- name: Remove Kernel Headers Available
  package:
    name: kernel-devel
    state: absent


#- name: Delete Lustre Server Repo
#  file:
#    path: /etc/yum.repos.d/lustre-repo.repo
#    state: absent

