---
# pvremove -y -ff /dev/vdb /dev/sda /dev/sdb

- name: Purge Block Devices
  shell: |
    dd if=/dev/zero of=/dev/{{ item.phy_dev }} bs=4096 count=1 conv=notrunc
  register: purge_block_devices
  when: item.node == inventory_hostname
  ignore_errors: true
  with_items:
    - "{{ _cluster.mgs }}"
    - "{{ _cluster.mdts }}"
    - "{{ _cluster.osts }}"
- debug: msg={{ purge_block_devices }}


- name: Wipe Filesystem in NVME Devices
  shell: |
    wipefs -a /dev/{{ item.phy_dev }}
  register: wipefs_nvme_devices
  when: item.node == inventory_hostname
  ignore_errors: true
  with_items:
    - "{{ _cluster.mgs }}"
    - "{{ _cluster.mdts }}"
    - "{{ _cluster.osts }}"
- debug: msg={{ wipefs_nvme_devices }}


- name: Delete Zap in NVME Devices
  shell: |
    sgdisk --zap-all --delete /dev/{{ item.phy_dev }}
  register: delete_zap_nvme_devices
  when: item.node == inventory_hostname
  ignore_errors: true
  with_items:
    - "{{ _cluster.mgs }}"
    - "{{ _cluster.mdts }}"
    - "{{ _cluster.osts }}"
- debug: msg={{ delete_zap_nvme_devices }}


- name: Discard Block ID
  shell: |
    blkdiscard /dev/{{ item.phy_dev }}
  register: discard_block_id
  when: item.node == inventory_hostname
  ignore_errors: true
  with_items:
    - "{{ _cluster.mgs }}"
    - "{{ _cluster.mdts }}"
    - "{{ _cluster.osts }}"
- debug: msg={{ discard_block_id }}

