---
- name: Stop and Disable LNET
  service:
    name: lnet
    state: stopped
    enabled: false
  register: disable_lnet
  ignore_errors: true


- name: Delete LNET Config
  file:
    path: /etc/lnet.conf
    state: absent
  register: delete_lnet_config
  ignore_errors: true

