---
- name: Enable Lustre Client Repo
  yum_repository:
    name: lustre-client
    description: lustre-client
    file: lustre-repo
    baseurl: "{{ _lustre.download_url }}/lustre-{{ lustre_version }}/{{ _lustre.os_version }}.{{ _lustre.os_minor_version }}/client"
    gpgcheck: no
  register: enable_client_repo
  when: inventory_hostname in groups['client']


- name: Enable Lustre Server Repo
  yum_repository:
    name: lustre-server
    description: lustre-server
    file: lustre-repo
    baseurl: "{{ _lustre.download_url }}/lustre-{{ lustre_version }}/{{ _lustre.os_version }}.{{ _lustre.os_minor_version }}/server"
    gpgcheck: no
  register: enable_server_repo
  when: inventory_hostname not in groups['client']


- name: Enable Lustre e2fs Repo
  yum_repository:
    name: e2fsprogs-wc
    description: e2fsprogs-wc
    file: lustre-repo
    baseurl: "https://downloads.whamcloud.com/public/e2fsprogs/latest/{{ _lustre.os_version }}"
    gpgcheck: no
  register: enable_e2fs_repo
  when: inventory_hostname not in groups['client']

