---
- name: Add Lustre Kernel Module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - lnet
    - lustre


- name: Configure LNET
  template:
    src: lnet.conf.j2
    dest: /etc/lnet.conf
  register: config_lnet


- name: Remove LNET Kernel Module
  shell: |
    /usr/sbin/lustre_rmmod


- name: Enable and Start LNET
  service:
    name: lnet
    state: restarted
    enabled: true
    daemon-reload: yes
  register: restart_lnet
  until: restart_lnet is succeeded
  retries: 10

