---
- name: Configure LNET
  template:
    src: lnet.conf.j2
    dest: /etc/lnet.conf
  register: config_lnet


- name: Enable and Start LNET
  service:
    name: lnet
    state: started
    enabled: true
  register: enable_lnet
