---
#- name: Configure and Enable Lnet
#  hosts: lustre_client,lustre_server
#  become: True
#  gather_facts: false
#  tasks:

- name: Write out lnet config
  template:
    src: lnet.conf.j2
    dest: /etc/lnet.conf
  register: lnetconf


- name: Ensure lnet is started
  service:
    name: lnet
    state: started
    enabled: true


# TODO: need tools to properly apply lnet to running config
# Also need tools to assert running config matches the file
#- name: Import lnet conf
#  command: "lnetctl import < /etc/lnet.conf"
#  when: lnetconf.changed


