---
- name: Create MGTs Mount Directory
  file:
    path: "{{ item.mnt_dir }}"
    state: directory
    recurse: yes
  loop: "{{ _cluster1.mgs }}"
  when: ( item.node == inventory_hostname ) and inventory_hostname in groups['mgs']


- name: Mount MGTs Directory
  shell: |
    mount -t lustre {{ item.dev_prefix }}/{{ item.dev }} {{ item.mnt_dir }}
  register: mount_mgts
  loop: "{{ _cluster1.mgs }}"
  when: ( item.node == inventory_hostname ) and inventory_hostname in groups['mgs']
- debug: msg="{{ mount_mgts }}"


- name: Create MDT Mount Directory
  file:
    path: /lustre/{{ item.fs }}/mdt/{{ item.dev }}
    state: directory
    recurse: yes
  loop: "{{ _cluster1.mdts }}"
  when: ( item.node == inventory_hostname ) and ( inventory_hostname in groups['mds'] or inventory_hostname in groups['dne'] )


- name: Mount MDTs Directory
  shell: |
    mount -t lustre {{ item.dev_prefix }}/{{ item.dev }} /lustre/{{ item.fs }}/mdt/{{ item.dev }}
  register: mount_mdts
  loop: "{{ _cluster1.mdts }}"
  when: ( item.node == inventory_hostname ) and ( inventory_hostname in groups['mds'] or inventory_hostname in groups['dne'] )
- debug: msg="{{ mount_mdts }}"


- name: Create OST Mount Directory
  file:
    path: /lustre/{{ item.fs }}/ost/{{ item.dev }}
    state: directory
    recurse: yes
  loop: "{{ _cluster1.osts }}"
  when: ( item.node == inventory_hostname ) and inventory_hostname in groups['oss']


- name: Mount OSTs Directory
  shell: |
    mount -t lustre {{ item.dev_prefix }}/{{ item.dev }} /lustre/{{ item.fs }}/ost/{{ item.dev }}
  register: mount_osts
  loop: "{{ _cluster1.osts }}"
  when: ( item.node == inventory_hostname ) and inventory_hostname in groups['oss']
- debug: msg="{{ mount_osts }}"


