---
- name: Ensure Mount Directory Exists
  file:
    path: "{{ item.mount_prefix }}/{{ item.fs_name }}"
    state: directory
    recurse: yes
  register: create_mount_dir
  with_items: "{{ _cluster.client }}"


# TODO: We should use the built in mount system in ansible
- name: Mount Lustre Filesystem
  shell: |
    mount -t lustre {{ item.mgsnode }}{{ item.lnet_suffix }}:/{{ item.fs_name }} {{ item.mount_prefix }}/{{ item.fs_name }}
  register: mount_lustrefs
  with_items: "{{ _cluster.client }}"


#- name: Mount Lustre Filesystem
#  mount:
#    fstype: lustre
#    src: "{{ item.mgsnode }}{{ item.lnet_suffix }}:/{{ item.fs_name }}"
#    path: "{{ item.mount_prefix }}/{{ item.fs_name }}"
#    state: mounted
#  register: mount_lustrefs
#  with_items: "{{ _cluster.client }}"
#  # opts: "skpath=/etc/lustre,defaults,_netdev,noauto,x-systemd.automount,x-systemd.requires=lnet.service"

