---
- name: Uninstall Lustre Client
  yum:
    name: "lustre-client-{{ lustre_version }}"
    state: absent
  register: uninstall_lustre_client
  when: inventory_hostname in groups['client']


- name: Uninstall Lustre Client Kernel Modules
  yum:
    name: "kmod-lustre-client-{{ lustre_version }}"
    state: absent
  register: uninstall_lustre_client_kernel_module
  when: inventory_hostname in groups['client']


- name: Uninstall Lustre Packages
  yum:
    name: "lustre-{{ lustre_version }}"
    state: absent
  register: uninstall_lustre_pkgs
  when: inventory_hostname not in groups['client']


- name: Uninstall Lustre Kernel Module Packages
  yum:
    name: "kmod-lustre-{{ lustre_version }},kmod-lustre-devel-{{ lustre_version }}"
    state: absent
  register: uninstall_lustre_kernel_module
  when: inventory_hostname not in groups['client']


- name: Uninstall Kernel Headers
  package:
    name: kernel-devel
    state: absent
  register: uninstall_kernel_headers
  when: inventory_hostname not in groups['client']


- name: Unload Lustre Kernel Module
  modprobe:
    name: lustre
    state: absent
  ignore_errors: true


- name: Delete LNET Config files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/lnet.conf"
    - "/etc/modprobe.d/lustre.conf"

