---
- import_tasks: ext/set-multipath-facts.yml


- name: Discover Target via Path 1
  shell: |
    iscsiadm -m discovery -t sendtargets -p {{ hostvars[groups['iscsi'][0]].ansible_ssh_host1 }}
  register: discover_target_path1


- name: Login to the Target via Path 1
  shell: |
    iscsiadm --mode node --target {{ _iscsi.target.iqn }}:{{ item.group }}.{{ item.name }} \
    --portal {{ hostvars[groups['iscsi'][0]].ansible_ssh_host1 }} --login
  register: login_target_path1
  when: item.client == inventory_hostname
  with_items: "{{ _iscsi.target.disks }}"


- name: Install Multipathd
  package:
    name: device-mapper-multipath
    state: present
  register: install_multipath_pkg


- name: Enable Multipath Config
  shell: |
    mpathconf --enable
  register: enable_multipath


- name: Copy Multipath Config Files
  template: src=multipath.conf.j2 dest=/etc/multipath.conf owner=root group=root mode=644 force=yes
  register: copy_multipath_conf


- name: Enable and Start Multipathd
  systemd:
    name: "{{ item }}"
    state: restarted
  register: restart_multipathd
  until: restart_multipathd is succeeded
  retries: 3
  delay: 10
  with_items:
    - "multipathd"

