---
- name: Check OS ( Single )
  fail: msg="Not a Red Hat based system!"
  when: ( ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky' ) and inventory_hostname in groups['lmtdb']


- name: Set Facts for Package Name and List and Network Range
  import_tasks: set-facts.yml
  tags: install, uninstall, init, enable, disable, config, stop, add
  when: inventory_hostname in groups['lmtdb']


- name: Enable PGDB Postgres Repository
  import_tasks: enable-repo.yml
  tags: enable, install
  when: (( repo is defined and repo == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Stop and Diable Firewalld and SELinux
  import_tasks: security/disable-security.yml
  tags: disable, install
  when: (( security is defined and security == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Install Common Prerequisties and PGDG Postgres RPM Packages
  import_tasks: install-pkgs.yml
  tags: install
  when: (( pkgs is defined and pkgs == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Initialize PGDG Postgres Instance
  import_tasks: init-pgsql.yml
  tags: init, install
  when: (( db is defined and db == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Create Database and Users
  import_tasks: add-users.yml
  tags: install, add
  when: (( user is defined and user == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Enable SSL for Single PGDG Postgres
  import_tasks: enable-ssl.yml
  tags: enable, config, install
  when: (( ssl is defined and ssl == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Check the status of Single PGDG Postgres
  import_tasks: check-status.yml
  tags: install
  when: (( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Stop and Disable PostgreSQL
  import_tasks: stop-pgsql-service.yml
  tags: uninstall, destroy, delete, stop
  when: (( service is defined and service == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Uninstall Common Prerequisties and PGDG Postgres RPM Packages
  import_tasks: uninstall-pkgs.yml
  tags: uninstall
  when: (( pkgs is defined and pkgs == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Enable Firewalld and SELinux
  import_tasks: security/enable-security.yml
  tags: enable, uninstall
  when: (( security is defined and security == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Remove config files of environment for Single PGDG Postgres
  import_tasks: remove-config-files.yml
  tags: uninstall, remove
  when: (( files is defined and files == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Disable PGDB Postgres Repository
  import_tasks: disable-repo.yml
  tags: disable, uninstall
  when: (( repo is defined and repo == true ) or ( postgres_all is defined and postgres_all == true )) and inventory_hostname in groups['lmtdb']


- name: Upgrade RPM Packages for Single PGDG Postgres
  import_tasks: upgrade.yml
  tags: upgrade
  when: inventory_hostname in groups['lmtdb']

