---
#- name: Delete Lustre Client Repo
#  file:
#    path: /etc/yum.repos.d/lustre-repo.repo
#    state: absent
#  register: delete_lustre_client_repo


- name: Delete IML Yum Repo
  file:
    path: "{{ item.fn }}"
    state: absent
  register: delete_iml_yum_repo
  with_items:
    - { fn: "/etc/yum.repos.d/CentOS-Base.repo" }
    - { fn: "/etc/yum.repos.d/chroma_support.repo" }
- debug: msg="{{ delete_iml_yum_repo }}"


- name: Clean Yum Package Caches
  shell:
    yum clean all
  register: clean_yum_pkg_caches
  ignore_errors: true
- debug: msg="{{ clean_yum_pkg_caches }}"

# yum-config-manager --enable <repo>

- name: List Yum Repository
  shell:
    yum repolist
  register: list_yum_repo
- debug: msg="{{ list_yum_repo }}"

