---
#- name: Enable Lustre Client Repo
#  yum_repository:
#    name: lustre-client
#    description: lustre-client
#    file: lustre-repo
#    baseurl: "{{ _lustre.download_url }}/lustre-{{ lustre_version }}/{{ _lustre.os_version }}.{{ _lustre.os_minor_version }}/client"
#    gpgcheck: no
#  register: enable_client_repo


- name: Copy IML Yum Repo Config Files
  template:
    src: "{{ item.fn }}"
    dest: "{{ item.dst }}"
    mode: 0644
  register: copy_iml_yum_repo
  with_items:
    - { fn: "CentOS-Base.repo.j2", dst: "/etc/yum.repos.d/CentOS-Base.repo" }
    - { fn: "chroma_support.repo.j2", dst: "/etc/yum.repos.d/chroma_support.repo" }
- debug: msg="{{ copy_iml_yum_repo }}"


# ls /etc/yum.repos.d/
#
#- name: Configure LNET
#  template:
#    src: lnet.conf.j2
#    dest: /etc/lnet.conf
#  register: config_lnet
#  until: config_lnet is succeeded
#  retries: 20
#  delay: 10


- name: Clean Yum Package Caches
  shell:
    yum clean all
  register: clean_yum_pkg_caches
- debug: msg="{{ clean_yum_pkg_caches }}"


- name: List Yum Repository
  shell:
    yum repolist
  register: list_yum_repo
- debug: msg="{{ list_yum_repo }}"

