---
- name: Install Yum Utils
  package:
    name: "yum-utils"
    state: present
  register: install_yum_utils
- debug: msg={{ install_yum_utils }}


- name: Install IML Packages
  package:
    name: "{{ item }}"
    state: present
  register: install_iml_pkgs
  with_items:
    - "postgresql96-contrib,postgresql96-server,grafana-12.0.1,python2-iml-manager,cargo"
- debug: msg={{ install_iml_pkgs }}
# rpmlib


- name: Move Postgres Data Directory
  shell: |
    mv /var/lib/pgsql/9.6/data /data/pgsql/data
  register: move_data_dir
- debug: msg={{ move_data_dir }}


- name: Create Symbolic Link
  file:
   src: "/data/pgsql/data"
   dest: "/var/lib/pgsql/9.6/data"
   state: link
  register: create_symlink
- debug: msg={{ create_symlink }}


# chroma-config setup


# Chroma
# http://192.168.2.71:443

# Grafana
# https://192.168.2.71:3000


#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive


#- name: Reboot Hosts to Apply New Kernel
#  import_tasks: ext/reboot-hosts.yml


