---
- name: Stop and Disable Services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  register: start_services
  ignore_errors: true
  # until: start_services is succeeded
  # retries: 3
  # delay: 10
  with_items:
    - "influxd"
    - "postgresql-9.6"
- debug: msg="{{ start_services }}"


- name: Remove Postgres Data Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/data/pgsql/data"
    - "/var/lib/pgsql/data"


- name: Uninstall IML Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_iml_pkgs
  with_items:
    - "postgresql96-contrib,postgresql96-server,rpmlib,grafana-12.0.1,python2-iml-manager"
- debug: msg="{{ uninstall_iml_pkgs }}"



# chroma-config setup


#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive


#- name: Reboot Hosts to Apply New Kernel
#  import_tasks: ext/reboot-hosts.yml


